#!/usr/bin/env bun
/** Generate the public method index from the normalized Telegram schema. */
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

type TelegramSchema = {
  readonly version: {
    readonly major: number;
    readonly minor: number;
    readonly release_date: {
      readonly year: number;
      readonly month: number;
      readonly day: number;
    };
  };
  readonly methods: readonly {
    readonly name: string;
    readonly anchor: string;
  }[];
  readonly objects: readonly { readonly name: string }[];
};

const root = resolve(import.meta.dir, "..");
const schema = JSON.parse(
  await readFile(resolve(root, ".generated-ir/telegram.json"), "utf8"),
) as TelegramSchema;
const version = `${schema.version.major}.${schema.version.minor}`;
if (version !== "10.3") {
  throw new Error(`Expected Telegram Bot API 10.3, got ${version}`);
}

const operationName = (method: string): string =>
  `${method[0]!.toUpperCase()}${method.slice(1)}`;
const releaseDate = [
  schema.version.release_date.year,
  String(schema.version.release_date.month).padStart(2, "0"),
  String(schema.version.release_date.day).padStart(2, "0"),
].join("-");

const lines = [
  "<!-- Generated by scripts/generate-docs.ts. Do not edit directly. -->",
  "",
  "# distilled-telegram API",
  "",
  `This reference is generated from the pinned **Telegram Bot API ${version}** ` +
    `snapshot released ${releaseDate}. It contains ${schema.methods.length} methods ` +
    `and ${schema.objects.length} documented Telegram object declarations.`,
  "",
  "Every method is exported from `distilled-telegram` as an Effect operation. " +
    "Its generated request, response, and typed error declarations use the " +
    "capitalized operation name shown below. For example, `sendMessage` is " +
    "paired with `SendMessageRequest`, `SendMessageResponse`, and " +
    "`SendMessageError`.",
  "",
  "| Method | Generated declarations | Telegram documentation |",
  "| --- | --- | --- |",
  ...schema.methods.map((method) => {
    const operation = operationName(method.name);
    return (
      `| \`${method.name}\` | \`${operation}Request\`, ` +
      `\`${operation}Response\`, \`${operation}Error\` | ` +
      `[source](https://core.telegram.org/bots/api${method.anchor}) |`
    );
  }),
  "",
  "Telegram names and snake-case wire fields are preserved. Generated response " +
    "schemas tolerate additive fields, while request schemas validate inputs " +
    "strictly. See the package README for credentials, files, retries, and error " +
    "handling.",
  "",
];

await writeFile(resolve(root, "API.md"), `${lines.join("\n")}\n`);
console.log(
  `Generated API.md for Telegram Bot API ${version} (${schema.methods.length} methods).`,
);
