#!/usr/bin/env bun
/** Generate the public method index from the normalized Telegram schema. */
import * as Schema from "effect/Schema";
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const TelegramSchema = Schema.Struct({
  version: Schema.Struct({
    major: Schema.Number,
    minor: Schema.Number,
    release_date: Schema.Struct({
      year: Schema.Number,
      month: Schema.Number,
      day: Schema.Number,
    }),
  }),
  methods: Schema.Array(
    Schema.Struct({
      name: Schema.String,
      anchor: Schema.String,
    }),
  ),
  objects: Schema.Array(Schema.Struct({ name: Schema.String })),
});

const root = resolve(import.meta.dir, "..");
const schema = Schema.decodeUnknownSync(TelegramSchema)(
  JSON.parse(
    await readFile(resolve(root, ".generated-ir/telegram.json"), "utf8"),
  ),
);
const version = `${schema.version.major}.${schema.version.minor}`;
if (version !== "10.3") {
  throw new Error(`Expected Telegram Bot API 10.3, got ${version}`);
}

const operationName = (method: string): string =>
  `${method[0]!.toUpperCase()}${method.slice(1)}`;
const releaseDate = [
  schema.version.release_date.year,
  String(schema.version.release_date.month).padStart(2, "0"),
  String(schema.version.release_date.day).padStart(2, "0"),
].join("-");

const lines = [
  "<!-- Generated by scripts/generate-docs.ts. Do not edit directly. -->",
  "",
  "# distilled-telegram API",
  "",
  `This reference is generated from the pinned **Telegram Bot API ${version}** ` +
    `snapshot released ${releaseDate}. It contains ${schema.methods.length} methods ` +
    `and ${schema.objects.length} documented Telegram object declarations.`,
  "",
  "Every method is exported from `distilled-telegram` as an Effect operation. " +
    "Its generated request, response, and typed error declarations use the " +
    "capitalized operation name shown below. For example, `sendMessage` is " +
    "paired with `SendMessageRequest`, `SendMessageResponse`, and " +
    "`SendMessageError`.",
  "",
  "| Method | Generated declarations | Telegram documentation |",
  "| --- | --- | --- |",
  ...schema.methods.map((method) => {
    const operation = operationName(method.name);
    return (
      `| \`${method.name}\` | \`${operation}Request\`, ` +
      `\`${operation}Response\`, \`${operation}Error\` | ` +
      `[source](https://core.telegram.org/bots/api${method.anchor}) |`
    );
  }),
  "",
  "Telegram names and snake-case wire fields are preserved. Generated response " +
    "schemas tolerate additive fields, while request schemas validate inputs " +
    "strictly. See the package README for credentials, files, retries, and error " +
    "handling.",
  "",
];

await writeFile(resolve(root, "API.md"), `${lines.join("\n")}\n`);
console.log(
  `Generated API.md for Telegram Bot API ${version} (${schema.methods.length} methods).`,
);
